### ISSUE TITLE
`graph` element overflows off-page

### ISSUE THREAD

**Issue by MyNameIsCosmo** [regexp-graph/regexp-editor#2]
If a long regular expression is rendered in the graph, the left side of the graph overflows off the page.

The fix for this is the following in the CSS:
```css
.graph {
    font-size: 22px;
    width: 100%;
}
```
